state_electors = {
    "Alaska": 3,
    "Arizona": 11,
    "Arkansas": 6,
    "California": 55,
    "Colorado": 9,
    "Connecticut": 7,
    "Delaware": 3,
    "District Of Columbia": 3,
    "Florida": 29,
    "Georgia": 16,
    "Hawaii": 4,
    "Idaho": 4,
    "Illinois": 20,
    "Indiana": 11,
    "Iowa": 6,
    "Kansas": 6,
    "Kentucky": 8,
    "Louisiana": 8,
    "Maine": 4,
    "Maryland": 10,
    "Massachusetts": 11,
    "Michigan": 16,
    "Minnesota": 10,
    "Mississippi": 6,
    "Missouri": 10,
    "Montana": 3,
    "Nebraska": 5,
    "Nevada": 6,
    "New Hampshire": 4,
    "New Jersey": 14,
    "New Mexico": 5,
    "New York": 29,
    "North Carolina": 15,
    "North Dakota": 3,
    "Ohio": 18,
    "Oklahoma": 7,
    "Oregon": 7,
    "Pennsylvania": 20,
    "Rhode Island": 4,
    "South Carolina": 9,
    "South Dakota": 3,
    "Tennessee": 11,
    "Texas": 38,
    "Utah": 6,
    "Vermont": 3,
    "Virginia": 13,
    "Washington": 12,
    "West Virginia": 5,
    "Wisconsin": 10,
    "Wyoming": 3,
}
states_hash = {
    'Alabama': 0,
    'Alaska': 0,
    'American Samoa': 0,
    'Arizona': 0,
    'Arkansas': 0,
    'California': 0,
    'Colorado': 0,
    'Connecticut': 0,
    'Delaware': 0,
    'District Of Columbia': 0,
    'Federated States Of Micronesia': 0,
    'Florida': 0,
    'Georgia': 0,
    'Guam': 0,
    'Hawaii': 0,
    'Idaho': 0,
    'Illinois': 0,
    'Indiana': 0,
    'Iowa': 0,
    'Kansas': 0,
    'Kentucky': 0,
    'Louisiana': 0,
    'Maine': 0,
    'Marshall Islands': 0,
    'Maryland': 0,
    'Massachusetts': 0,
    'Michigan': 0,
    'Minnesota': 0,
    'Mississippi': 0,
    'Missouri': 0,
    'Montana': 0,
    'Nebraska': 0,
    'Nevada': 0,
    'New Hampshire': 0,
    'New Jersey': 0,
    'New Mexico': 0,
    'New York': 0,
    'North Carolina': 0,
    'North Dakota': 0,
    'Ohio': 0,
    'Oklahoma': 0,
    'Oregon': 0,
    'Palau': 0,
    'Pennsylvania': 0,
    'Puerto Rico': 0,
    'Rhode Island': 0,
    'South Carolina': 0,
    'South Dakota': 0,
    'Tennessee': 0,
    'Texas': 0,
    'Utah': 0,
    'Vermont': 0,
    'Virgin Islands': 0,
    'Virginia': 0,
    'Washington': 0,
    'West Virginia': 0,
    'Wisconsin': 0,
    'Wyoming': 0
}
state_chance_hillary_pi = {
    'Alabama': 2,
    'Alaska': 8,
    'Arizona': 26,
    'Arkansas': 1,
    'California': 95,
    'Colorado': 70,
    'Connecticut': 95,
    'Delaware': 95,
    'District Of Columbia': 98,
    'Florida': 60,
    'Georgia': 26,
    'Hawaii': 95,
    'Idaho': 1,
    'Illinois': 85,
    'Indiana': 15,
    'Iowa': 59,
    'Kansas': 1,
    'Kentucky': 5,
    'Louisiana': 2,
    'Maine': 95,
    'Maryland': 98,
    'Massachusetts': 95,
    'Michigan': 65,
    'Minnesota': 97,
    'Mississippi': 1,
    'Missouri': 1,
    'Montana': 2,
    'Nebraska': 1,
    'Nevada': 66,
    'New Hampshire': 59,
    'New Jersey': 95,
    'New Mexico': 85,
    'New York': 85,
    'North Carolina': 44,
    'North Dakota': 5,
    'Ohio': 54,
    'Oklahoma': 5,
    'Oregon': 96,
    'Pennsylvania': 61,
    'Rhode Island': 95,
    'South Carolina': 5,
    'South Dakota': 5,
    'Tennessee': 1,
    'Texas': 0,
    'Utah': 35,
    'Vermont': 95,
    'Virginia': 64,
    'Washington': 95,
    'West Virginia': 5,
    'Wisconsin':65,
    'Wyoming': 5
  }

sc_obama_nate = {
    'Alabama': 0,
    'Alaska': 0,
    'Arizona': 2,
    'Arkansas': 0,
    'California': 100,
    'Colorado': 80,
    'Connecticut': 100,
    'Delaware': 100,
    'District Of Columbia': 100,
    'Florida': 50,
    'Georgia': 0,
    'Hawaii': 100,
    'Idaho': 0,
    'Illinois': 100,
    'Indiana': 0,
    'Iowa': 84,
    'Kansas': 0,
    'Kentucky': 0,
    'Louisiana': 0,
    'Maine': 100,
    'Maryland': 100,
    'Massachusetts': 100,
    'Michigan': 99,
    'Minnesota': 100,
    'Mississippi': 0,
    'Missouri': 0,
    'Montana': 2,
    'Nebraska': 0,
    'Nevada': 93,
    'New Hampshire': 85,
    'New Jersey': 100,
    'New Mexico': 99,
    'New York': 100,
    'North Carolina': 26,
    'North Dakota': 0,
    'Ohio': 91,
    'Oklahoma': 0,
    'Oregon': 100,
    'Pennsylvania': 99,
    'Rhode Island': 100,
    'South Carolina': 0,
    'South Dakota': 0,
    'Tennessee': 0,
    'Texas': 0,
    'Utah': 0,
    'Vermont': 100,
    'Virginia': 79,
    'Washington': 100,
    'West Virginia': 0,
    'Wisconsin': 97,
    'Wyoming': 0
}